ADD: POST user/views.py
wecode-bootcamp-korea/17-1st-WeGotDiz-backend pull request #3
Opened 2021-02-19 15:24 UTC by mjhuh263

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 기능을 POST 메소드로 구현했습니다. 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일은 unique=True로 이미 존재하는 이메일은 회원가입 못하게 막았습니다.
- 비밀번호는 validation을 이용해 와디즈 사이트와 동일하게 '영문, 숫자, 특수문자 (!@#$%^&*+=-)를 조합한 8자 이상'으로 만들었습니다.
- maker_info는 사용자가 회원가입 후 신청하는 항목이기 때문에 None 값을 받도록 설정했습니다. 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-19 15:34 UTC, mjhuh263 commented
제목 오타입니다.. 오해하시면 안돼요... 죄송합니다..😭😭😭😭😭😭😭😭😭😭😭😭😭😭

2021-02-20 16:31 UTC, jamessoun93 requested changes

2021-02-20 16:31 UTC, jamessoun93 commented on .vscode/settings.json
> +}
.vscode 폴더 또올라왔네요! gitignore 세팅 재확인해주시고 이전과 같이 해당 폴더 없애주시기 바랍니다 🙏

2021-02-20 16:31 UTC, jamessoun93 commented on user/views.py
> +)
- 큰 문제가 되는것은 아니지만 import 문 기준으로 정렬해주실 때 굳이 저렇게 space 를 많이주실 필요없이 해당 block 에서 가장 긴 from 문 기준으로 잡아주시면 깔끔합니다! 
- 그리고 아래 user.models import 문 구분 잘 해주셨는데 현재 모델 class를 하나만 import 해오는 과정이니 굳이 괄호를 추가해 아래로 정렬해주실 필요까지 없을 것 같아 아래와 같이 수정해봤습니다.
```suggestion
from django.http  import JsonResponse, HttpResponse
from django.views import View

from user.models import User
```

2021-02-20 16:31 UTC, jamessoun93 commented on user/views.py
> +email_regex              = re.compile(r'^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$')
넘겨받은 email 주소가 유효한 email 주소인지 판별하기 위한 validation 로직을 구현하기 위해 정규표현식 잘 사용하셨습니다 👏 
이렇게 직접 구현하시는 것도 좋지만, Django 자체적으로 제공되는 validators 가 존재한다는걸 아시나요?! 특히 `validate_email` 이라는 validator 는 Django 소스코드에서 해당 부분을 살펴보면 실제로 정규표현식을 이미 사용하고 있습니다. 한번 살펴보시고 import 해서 사용해보시는 것도 추천드립니다. (코드가 간결해지거든요 😉 )

2021-02-20 16:31 UTC, jamessoun93 commented on user/views.py
> +            fullname     = data['fullname']
```suggestion
            full_name    = data['full_name']
```

2021-02-20 16:31 UTC, jamessoun93 commented on user/views.py
> +            maker_info   = data.get('maker_info', None)
None 은 default 라서 굳이 필요하지 않습니다~! 하지만 가독성을 위해 일부러 추가하신거라면 굳이 수정하지 않으셔도 됩니다.
```suggestion
            maker_info   = data.get('maker_info')
```

2021-02-20 16:31 UTC, jamessoun93 commented on user/views.py
> +                return JsonResponse({"message" : "PASSWORD_REQUIRED"}, status=400)
작성하신 코드에서 `email`, `full_name`, `password` 중 한가지라도 들어오지 않았을 경우 이쪽 부분의 코드가 실행이 될까요? 한번 생각해보시고 답변 달아주세요 😀

2021-02-20 16:31 UTC, jamessoun93 commented on user/views.py
> +                return JsonResponse({"message" : "EMAIL_VALIDATION"}, status=400)
`email_regex.search(email)`의 결과값이 Falsy value 인 경우 유효하지 않은 이메일 주소라는 뜻이니, JSON response 의 메세지를 조금 더 명확하게 지어주시는게 좋겠네요. 아래처럼요!
```suggestion
            if not email_regex.search(email):
                return JsonResponse({"message" : "INVALID_EMAIL"}, status=400)
```

2021-02-20 16:31 UTC, jamessoun93 commented on user/views.py
> +                return JsonResponse({"message" : "PASSWORD_VALIDATION"}, status=400)
위와 마찬가지입니다!

2021-02-20 16:31 UTC, jamessoun93 commented on user/views.py
> +            hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
👏 👏 👏

2021-02-20 16:31 UTC, jamessoun93 commented on user/views.py
> +                maker_info=maker_info
가독성을 위해 `=` 을 기준으로 정렬해주세요!

2021-02-20 16:31 UTC, jamessoun93 commented on user/views.py
> +            return JsonResponse({"message" : "SUCCESS"}, status=200)
회원가입이 정상적으로 처리되었다는 뜻은 새로운 유저가 데이터베이스에 성공적으로 CREATE 되었다는 뜻이니 그 뜻을 포함하고 있는 status code 를 return 해주세요!

2021-02-20 17:10 UTC, mjhuh263 commented on .vscode/settings.json
> +}
헉.... 다음부터 꼭 확인하겠습니다!  🧤

2021-02-20 17:10 UTC, mjhuh263 commented on user/views.py
> +)
넵! 수정하겠습니다 :)

2021-02-20 17:13 UTC, mjhuh263 commented on user/views.py
> +email_regex              = re.compile(r'^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$')
넵! 바로 적용시키겠습니다~~~ 🐹

2021-02-20 17:17 UTC, mjhuh263 commented on user/views.py
> +            fullname     = data['fullname']
헉 `fullname`을 models.py 속에도 언더스코어 없이 설정했습니다...!😭😭 변수만 언더스코어로 스페이스를 줘도 될까요..? ㅠㅠ

2021-02-20 17:18 UTC, mjhuh263 commented on user/views.py
> +            maker_info   = data.get('maker_info', None)
아닙니다 수정하겠습니다 :)!

2021-02-20 17:20 UTC, mjhuh263 commented on user/views.py
> +                return JsonResponse({"message" : "EMAIL_VALIDATION"}, status=400)
헉 지금 수정하겠습니다! 명확한... 메세지... 메모... 📝

2021-02-20 17:21 UTC, mjhuh263 commented on user/views.py
> +            hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
여기도 `INVALID:PASSWORD`으로 수정하겠습니다~~~ 🙏

2021-02-20 17:22 UTC, mjhuh263 commented on user/views.py
> +                maker_info=maker_info
헉 수정하겠습니다!😭

2021-02-20 17:25 UTC, mjhuh263 commented on user/views.py
> +            return JsonResponse({"message" : "SUCCESS"}, status=200)
말도 안돼... 201이라고 안썼다니....🤯 수정하겠습니다!!!

2021-02-20 17:34 UTC, mjhuh263 commented
안녕하세요 승현님! 장고 프로젝트 파일의 urls.py를 수정하고 커밋해도 DELETE으로 다시 취소되는데...  원래 DELETE 되는게 정상인가요..? 늦은 시간까지 항상 감사합니다...😭

2021-02-20 17:37 UTC, jamessoun93 commented
민지님 이것도 꼭 열어서 확인해주세요~!
![스크린샷 2021-02-21 오전 2 36 31](https://user-images.githubusercontent.com/50141312/108603860-a190d900-73ed-11eb-89b5-1e49bf75c454.png)

2021-02-20 17:37 UTC, jamessoun93 commented
> 안녕하세요 승현님! 장고 프로젝트 파일의 urls.py를 수정하고 커밋해도 DELETE으로 다시 취소되는데... 원래 DELETE 되는게 정상인가요..? 늦은 시간까지 항상 감사합니다...😭

2021-02-20 17:38 UTC, jamessoun93 commented
> 안녕하세요 승현님! 장고 프로젝트 파일의 urls.py를 수정하고 커밋해도 DELETE으로 다시 취소되는데... 원래 DELETE 되는게 정상인가요..? 늦은 시간까지 항상 감사합니다...😭

민지님 커밋해도 수정내용이 반영이 안된다는 말씀이신가요?

2021-02-20 17:41 UTC, mjhuh263 commented
> @mjhuh263 민지님 이것도 꼭 열어서 확인해주세요~! 혹시 못보셨을까봐 말씀드립니다!
> ![스크린샷 2021-02-21 오전 2 36 31](https://user-images.githubusercontent.com/50141312/108603860-a190d900-73ed-11eb-89b5-1e49bf75c454.png)

어떻게 아셨죠.. ㅠㅠ

2021-02-20 17:44 UTC, mjhuh263 commented
> > 안녕하세요 승현님! 장고 프로젝트 파일의 urls.py를 수정하고 커밋해도 DELETE으로 다시 취소되는데... 원래 DELETE 되는게 정상인가요..? 늦은 시간까지 항상 감사합니다...😭
> 
> @mjhuh263 민지님 커밋해도 수정내용이 반영이 안된다는 말씀이신가요?

앗 이 부분은 오늘 다른 팀원들 파일에서 다시 확인해보고 코멘트 남기겠습니다!!! 😭

2021-02-20 17:47 UTC, mjhuh263 commented on user/views.py
> +                return JsonResponse({"message" : "PASSWORD_REQUIRED"}, status=400)
흑.... 아니요....... 수정하겠습니다 ㅠㅠ

2021-02-21 14:28 UTC, jamessoun93 commented on user/views.py
> +            fullname     = data['fullname']
넵넵!

2021-02-23 01:15 UTC, jamessoun93 commented
> 예에에에에에전에 지훈님께서 validators도 utils.py처럼 따로 파일로 관리할 수 있다고 하셨던 것 같아서 이렇게 구현했습니다..! 하지만 함수가 한개 밖에 없어서... 외로운 함수...validator가 딱 한개라 ㅠㅠ 이렇게 해도 되는지.. 모르겠습니다 ㅠㅠ
잘하셨습니다! validator 는 따로 파일 분리해서 유지보수 해주시는게 좋아요!

2021-02-23 01:18 UTC, jamessoun93 approved these changes
LGTM

2021-02-23 01:18 UTC, jamessoun93 commented on user/validators.py
> +from django.http              import JsonResponse
불필요한 spacing 없애주시고 이렇게 두줄 정도밖에 안되는 import 문이면 굳이 띄어주실 필요까지 없을 것 같아요!

2021-02-23 01:19 UTC, merged

2021-02-23 01:23 UTC, mjhuh263 commented on user/validators.py
> +from django.http              import JsonResponse
넵!!🙏