[17기 최호진] ADD: PurchaseStep1View, PurchaseStep2View
wecode-bootcamp-korea/17-1st-WeGotDiz-backend pull request #4
Opened 2021-02-20 02:18 UTC by jenehojinchoi

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- PurchaseStep1View, PurchaseStep2View 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- PurchaseStep1View: GET으로 클라이언트에게 결제 전 reward 리스트를 보내주는 뷰
- PurchaseStep2View: POST로 유저가 만든 결제 내역을 db에 업데이트, reward 남은 수량(재고) 업데이트, product 총 펀딩된 금액 업데이트

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- View 이름을 바꾸어야할까요...? 
- 아직 urls.py를 작성하지 않았습니다. 추가 사항이 생기거나 urls.py 를 추가하게 되면 다시 커밋하겠습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-20 17:31 UTC, jamessoun93 requested changes
호진님~! 
- 전반적으로 코드가 깔끔해서 잘 읽히네요 👏 👏 👏
- 하지만 뭔가 view 작성 뒤 모든 부분 제대로 작동하는지 테스트가 덜 된 상태로 올라온듯한 부분들이 보여서 리뷰 남겨드렸으니 반영해서 push 해주시고, 앞으로는 test 꼼꼼하게 해보신 후 push 해주세요! 😀

2021-02-20 17:31 UTC, jamessoun93 commented on purchase/views.py
> +from user.utils      import login_decorator
깔끔하네요~ ✨  👏 👏 👏

2021-02-20 17:31 UTC, jamessoun93 commented on user/utils.py
> +from models                   import User
import 문 기준으로 정렬 너무 깔끔하게 잘해주셨네요! 하지만 각 줄마다 space 가 과도하게 많아서 붙여주세요~!

2021-02-20 17:31 UTC, jamessoun93 commented on user/utils.py
> +    return wrapper
- 작성하신 decorator 제대로 작동하는지 확인해보셨을까요? 🤔
- 어디에 문제가 있는지 찾아보시고 수정하신 뒤 꼭 test 해보시고 push 해주세요~

2021-02-20 17:31 UTC, jamessoun93 commented on purchase/views.py
> +class PurchaseStep1View(View):
class 이름을 보고 해당 view class 가 어떤 로직을 담고 있는지 알 수 있어야하는데, 구매단계들 중 첫번째 단계를 담당하는 view class 라는 정보로는 어떤 로직을 담당하는지 정확하게 알기가 힘듭니다. class 명 수정해주세요! 😉

2021-02-20 17:31 UTC, jamessoun93 commented on purchase/views.py
> +    def get(self, request, product_id):
현재 main 브랜치에 있는 코드와 올려주신 코드들로는 `product_id` 를 정상적으로 받아올 수가 없을텐데요! 꼭 test 하고 push 해주셔야합니다 😀

2021-02-20 17:31 UTC, jamessoun93 commented on purchase/views.py
> +        return JsonResponse({'rewards_list': rewards_list}, status=201)
- Exception 을 발생시킬 수 있는 method 를 사용하셨는데, 발생 시 어떻게 handle 할지를 담고있는 로직이 빠졌네요 😅
- Exception 이 발생했는데 아무런 처리를 해주지 않는다면 client 입장에서는 문제가 있었다는 사실 외에 아무런 정보를 알수가 없습니다. 
- 위 코드에서 raise 될 수 있는 Exception 을 찾아보시고 수정해주세요 😉

2021-02-20 17:31 UTC, jamessoun93 commented on purchase/views.py
> +            )
- 굳~ 👏 👏 👏  
- 이 부분 `list comprehension` 으로 변경해보시겠어요? 😉  
- `list comprehension` 으로 변경 뒤 호진님이 판단하시기에 어떤점이 달라졌는지 comment 남겨주세요 😀

2021-02-20 17:31 UTC, jamessoun93 commented on purchase/views.py
> +    def post(self, request, product_id):
위의 product_id 부분 comment 내용과 같습니다 🙏

2021-02-20 17:31 UTC, jamessoun93 commented on purchase/views.py
> +class PurchaseStep2View(View):
위의 class 명 관련 comment 내용과 같습니다!

2021-02-20 17:31 UTC, jamessoun93 commented on purchase/views.py
> +            total_amount         = data['total_amount']
- `data['reward_quantity']` 를 `reward_quantity_list` 라는 변수에 할당해주셨는데, `list` 인지 `integer` 인지에 따라 명확한 변수명으로 변경해주세요!
- `reward_quantity_list = data['reward_quantity'] 는 아래 중복으로 작성되어있네요!`
- dictionary methods 중 `get()` 은 지정하신 key로 조회했을 때 값이 존재하지 않는다면 default 로 None 을 return 하게되므로 가독성을 위해 적어주신게 아니라면 불필요합니다!

2021-02-20 17:31 UTC, jamessoun93 commented on purchase/views.py
> +            return JsonResponse({'message': "NO_INFORMATION"}, status = 401)
PurchaseStep1View 의 리뷰 내용 중 Exception 핸들링에 대한 내용 참고하시고 여기서도 같은 Exception 핸들링 로직 추가해주세요 😉

2021-02-20 17:31 UTC, jamessoun93 commented on purchase/views.py
> +            if address == None:
`==` 은 equality operator 로 주로 값을 비교할 때 사용합니다. 하지만 Python 에서 `None` 은 `NoneType` 클래스의 instance 객체로 따로 값이 존재하지 않습니다. 따라서 `NoneType` 인지 확인하고 싶으실 때는 identity operator 인 `is` 를 사용해주세요 😎

(`identity operator` 는 비교대상이 서로 같은 memory address 를 reference 하고 있는지 비교하고, `equality operator` 는 비교대상이 reference 하고 있는 memory address 에 담긴 값을 비교합니다 😁 )

2021-02-20 17:31 UTC, jamessoun93 commented on purchase/views.py
> +                return JsonResponse({'message': "INVALID_ADDRESS"}, status = 401)
이 부분 로직 흐름을 정리해보자면,
- client 에서 address 정보를 넘겨주지 않았을 경우
- 해당 유저의 address 목록을 조회해서 첫번째 주소를 사용하고
- address 목록에 데이터 존재 여부에 상관없이 "INVALID_ADDRESS" 를 `UNAUTHORIZED` 를 의미하는 `401` 과 함께 반환한다.

뭔가 이상하죠!? 확인 후 수정 부탁드리겠습니다 🙏

2021-02-20 17:31 UTC, jamessoun93 commented on purchase/views.py
> +            address = Address.objects.get_or_create(user_id=user_id, address=data['address'])[0]
- `get_or_create` 사용 잘하셨네요 👏 👏 👏
- tuple 에서 0번 index 값 꺼내서 저장하는 디테일까지 🥳

2021-02-20 17:31 UTC, jamessoun93 commented on purchase/views.py
> +            product.save()
이 부분은 `reward_quantity` 와 `reward_quantity_list` 가 정확히 어떤 정보들인지 설명해주시면 파악 후 review 를 작성할 수 있을 것 같습니다. 변수명만 보고 판단이 잘 안되서요. comment 로 남겨주세요 🙏

2021-02-20 17:33 UTC, jamessoun93 commented on purchase/views.py
> +    def get(self, request, product_id):
> 지금 메인 페이지가 구현되고 있어서 이틀 내에 urls.py를 추가하겠습니다. 추가 사항이 생기거나 urls.py 를 추가하게 되면 다시 커밋하겠습니다.
- 남겨주신 내용을 리뷰 다 남긴 뒤 확인했네요 😅  하지만 push 하실 때는 꼭 정상작동하는걸 확인하신 후 해주셔야 하기 때문에 `urls.py` 추가해서 올려주세요!

2021-02-20 17:34 UTC, jamessoun93 commented on purchase/views.py
> +class PurchaseStep1View(View):
> View 이름을 바꾸어야할까요...?
- 리뷰 다 남기고 나서 확인을 해버렸네요.. 😅  리뷰내용 확인해주세요!

2021-02-21 00:48 UTC, jenehojinchoi commented on purchase/views.py
> +from user.utils      import login_decorator
다 승현님 덕분이에요 후후 감사합니다!

2021-02-21 00:48 UTC, jenehojinchoi commented on user/utils.py
> +from models                   import User
앗 넵! 정정하겠습니다

2021-02-21 00:50 UTC, jenehojinchoi commented on user/utils.py
> +    return wrapper
앗 로그인 데코레이터는 아직 테스트를 안 해보았습니다. 담부터는 꼭 테스트하고 올리겠습니다...! 피드백 감사합니다! 다시 제대로 테스트 해보고 수정하겠습니다.

2021-02-21 00:51 UTC, jenehojinchoi commented on purchase/views.py
> +class PurchaseStep1View(View):
넵 클래스 이름도 더 알아듣기 쉽게 바꾸겠습니다! 변수명 정하기가 어렵네요...

2021-02-21 00:53 UTC, jenehojinchoi commented on purchase/views.py
> +    def get(self, request, product_id):
한 product의 디테일 페이지(?)를 가서 결제를 하는 것이기 때문에 url에서 product_id를 받을 예정입니다. urls.py에 수정하여 올리겠습니다!

2021-02-21 00:54 UTC, jenehojinchoi commented on purchase/views.py
> +            return JsonResponse({'message': "NO_INFORMATION"}, status = 401)
넵 정정하겠습니다!! 😊😊

2021-02-21 00:55 UTC, jenehojinchoi commented on purchase/views.py
> +            if address == None:
세상에....! 제가 멋 모르고 썼던 점 짚어주셔서 감사합니다...! 담부터는 더 꼼꼼한 코드로 돌아올게요..!

2021-02-21 00:59 UTC, jenehojinchoi commented on purchase/views.py
> +                return JsonResponse({'message': "INVALID_ADDRESS"}, status = 401)
넵! 수정하겠습니다...!!!

2021-02-21 01:03 UTC, jenehojinchoi commented on purchase/views.py
> +            product.save()
reward_quantity는 유저가 결제하는 한 reward당 수량이고, reward_quantity_list는 각 reward의 id와 그 reward의 quantity가 담긴 리스트입니다. (e.g.) '[{"reward":1, "quantity":3}, {"reward":2, "quantity":2}]'

2021-02-21 01:07 UTC, jenehojinchoi commented on purchase/views.py
> +        return JsonResponse({'rewards_list': rewards_list}, status=201)
네엡...! 정정하겠습니다!!

2021-02-21 01:08 UTC, jenehojinchoi commented on purchase/views.py
> +            )
넵! 이것도 수정하고 코멘트 남기도록 하겠습니다!

2021-02-21 01:09 UTC, jenehojinchoi commented on purchase/views.py
> +            total_amount         = data['total_amount']
앗 넵 중복된 부분은 삭제하였습니다. 뒤에 있는 None도 삭제하도록 하겠습니다!

2021-02-21 06:47 UTC, jenehojinchoi commented on purchase/views.py
> +                return JsonResponse({'message': "INVALID_ADDRESS"}, status = 401)
로직은 맞는것 같은데 status code 를 400으로 바꾸면 되는 것인가요?? 🧐🧐

2021-02-21 14:26 UTC, jenehojinchoi commented on purchase/views.py
> +            product.save()
지금 다시 보니 이름도 좀 이상한거 같네요 ...ㅎ.... 변수명도 좀 바꿔보겠습니다....

2021-02-21 14:34 UTC, jamessoun93 commented on purchase/views.py
> +            product.save()
일단 설명해주신 것 잘 이해했습니다 호진님!
그런데 reward의 id 만 프론트에 보내주면 프론트에서 해당 reward 가 어떤 reward 인지 알 수가 없지 않을까요?!

2021-02-21 14:55 UTC, jenehojinchoi commented on purchase/views.py
> +            product.save()
앗.....!!!!!!!!!!!!!!!!! 😳😳😳😳😳😳😳 클라이언트를 전혀 고려하지 않아버렸네요...!! 수정하겠습니다!

2021-02-23 01:49 UTC, jamessoun93 requested changes

2021-02-23 01:49 UTC, jamessoun93 commented on .gitignore
> +csv
`*.csv` 의 형태로 넣어주시면 모든 csv 확장자 파일이 gitignore에 따라 git이 트랙을 하지 않게 됩니다!

2021-02-23 01:49 UTC, jamessoun93 commented on purchase/views.py
> +        for reward in rewards]
👍👍👍

2021-02-23 01:49 UTC, jamessoun93 commented on purchase/views.py
> +                return JsonResponse({'message':'PRODUCT_NOT_FOUND'}, status=404)
👍👍👍

2021-02-23 01:49 UTC, jamessoun93 commented on purchase/views.py
> +            total_amount         = data['total_amount']
사용자가 funding 한 금액이라면 변수명 수정해주셔야할 것 같습니다!! 😉

2021-02-23 01:49 UTC, jamessoun93 commented on purchase/views.py
> +                total_amount   = total_amount
위에서 변수명 바뀌면 그거에 맞게 변경해주세요~ 👍

2021-02-23 01:49 UTC, jamessoun93 commented on purchase/views.py
> +                reward   = Reward.objects.get(name=name)
`name_quantity_list` 가 어떤 식으로 들어오는지 comment 로 남겨주실 수 있나요?

2021-02-23 01:49 UTC, jamessoun93 commented on purchase/views.py
> +                return JsonResponse({'message': "ADDRESS_NEEDED"}, status = 400)
`status = 400` or `status=400` 
프로젝트 전체적으로 `=` 앞뒤 spacing 통일시켜주세요 :)

2021-02-23 01:49 UTC, jamessoun93 commented on purchase/views.py
> +            return JsonResponse({'message': "NO_INFORMATION"}, status = 400)
exception 이렇게 잡아주시면 어떤 exception 이 raise 되어도 이쪽으로 오게되서 좋은 방법이 아닙니다 호진님! 
정확하게 어디서 어떤 exception 이 발생하는지 모른채로 다 잡아주게 되면, 디버깅할때 시간이 10배는 걸릴 수 있습니다. 어떤 에러가 발생할 수 있는지 모르겠으면 직접 여러가지 에러 발생 case 를 직접 테스트해서 찾아주시는 방법이 있습니다 😉

2021-02-23 01:50 UTC, jamessoun93 commented
첫 conflict 발생! 수정해서 push 해보시죠 😄

2021-02-23 02:05 UTC, jenehojinchoi commented on purchase/views.py
> +            total_amount         = data['total_amount']
넵!!

2021-02-23 02:05 UTC, jenehojinchoi commented on purchase/views.py
> +                total_amount   = total_amount
넵!!!

2021-02-23 02:06 UTC, jenehojinchoi commented on purchase/views.py
> +                return JsonResponse({'message': "ADDRESS_NEEDED"}, status = 400)
넵! 통일시키겠습니다!

2021-02-23 02:06 UTC, jenehojinchoi commented on purchase/views.py
> +                reward   = Reward.objects.get(name=name)
name_quantity:='[{"name":"[얼리버드]", "quantity":3}, {"name":"[슈퍼 얼리버드]", "quantity":2}]'

같이 들어옵니다!

2021-02-23 02:07 UTC, jenehojinchoi commented on purchase/views.py
> +            return JsonResponse({'message': "NO_INFORMATION"}, status = 400)
앗 넵...! 그렇다면 except Exception as e 쓰는 것은 어떻게 생각하시나요?  그냥 하나하나 잡는 것이 좋을까요?

2021-02-25 10:44 UTC, jenehojinchoi commented
conflict 사항 수정하고 push 했는데 push 가 작동하지 않아서 force push를 진행하였습니다. push된 파일들 한번 확인해주시고 merge 부탁드려요 감사합니다!!! ><

2021-02-25 12:30 UTC, jamessoun93 commented
LGTM

2021-02-25 12:31 UTC, merged