ADD: SignInView user/views.py
wecode-bootcamp-korea/17-1st-WeGotDiz-backend pull request #5
Opened 2021-02-20 08:03 UTC by mjhuh263

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 앤드포인트 구현했습니다. 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- DB에 저장되어 있는 해쉬된 패스워드와 사용자가 입력한 패스워드를 compare 후 access_token을 발행할 수 있게 설정했습니다. 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-21 05:31 UTC, mjhuh263 commented
login decorator 오타, status code 수정 후 다시 PR 올리겠습니다!ㅠㅠ

2021-02-21 05:32 UTC, mjhuh263 commented
import spacing도 수정하겠습니다..

2021-02-22 01:43 UTC, jamessoun93 requested changes

2021-02-22 01:43 UTC, jamessoun93 commented on user/utils.py
> +            return JsonResponse({"message" : "INVALID_USER"}, status=400)
더 의미에 알맞는 status code 가 존재합니다 😉 찾아서 적용해주세요!

2021-02-22 01:43 UTC, jamessoun93 commented on user/views.py
> +            return JsonResponse({"message" : "INVALID_USER"}, status=400)
이런식으로 if 문이 nest 되는 방식보다, 해당 유저를 찾을 수 없을때만 Exception 을 raise 해주시는 방법이 가독성에 좋습니다. 수정해보세요!

2021-02-22 21:08 UTC, mjhuh263 commented on user/utils.py
> +            return JsonResponse({"message" : "INVALID_USER"}, status=400)
넵~~~ 찾아보겠습니다🙏

2021-02-22 21:09 UTC, mjhuh263 commented on user/views.py
> +            return JsonResponse({"message" : "INVALID_USER"}, status=400)
지금 바로 수정하겠습니다! 🥎🔥

2021-02-23 13:19 UTC, jamessoun93 approved these changes
LGTM

2021-02-23 13:19 UTC, merged

2021-02-23 15:44 UTC, mjhuh263 commented
감사합니다!