[17기 이지윤] CREATE: ProductDetailView, LikeView
wecode-bootcamp-korea/17-1st-WeGotDiz-backend pull request #7
Opened 2021-02-23 01:46 UTC by yoon1ee

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 좋아요 기능 구현
- 프로덕트 디테일 페이지 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- N/A

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-23 14:22 UTC, jamessoun93 requested changes

2021-02-23 14:22 UTC, jamessoun93 commented on product/urls.py
> +# ]
지윤님 push 하실때는 꼭 불필요한 주석 없애고 올려주세요!! 😉

2021-02-23 14:22 UTC, jamessoun93 commented on product/views.py
> +
빈줄 굳이 이렇게 많이 추가 안해주셔도 됩니다 지윤님~ 😉

2021-02-23 14:22 UTC, jamessoun93 commented on product/views.py
> +            popularity_level    = product.maker_info.popularity_level
지윤님 하나하나 변수에 저장해주시느라 넘 고생하셨네요 👏

관련하여 코멘트 드리자면, `product.category_set.all()[0].name` 혹은 `product.productcontent_set.all()` 같은 정보는 변수에 할당해주므로 가독성이 좋아지는 효과를 볼 수 있지만, 그 외 `product.title`, `product.description` 같은 정보들은 사용하는 곳에서 직접 접근해주시는게 불필요한 변수 생성없이 가독성도 좋은 방법이라고 생각합니다.

수정해보세요!! 😉

2021-02-23 14:22 UTC, jamessoun93 commented on product/views.py
> +                tab_names.append(content.name)
`list comprehension` 적용하기 좋은 예시네요! 적용해보세요~

2021-02-23 14:22 UTC, jamessoun93 commented on product/views.py
> +            ]
이 부분들도 굳이 위에서 선언하여 아래에서 불러주실 필요까지없이 아래 결과 dictionary를 생성할때 바로 생성하여 해당 dictionary 의 프로퍼티로 만들어주시는게 좋습니다. 해당 변수를 다른데서 쓰지 않는데 굳이 변수화해줄 이유도 없고, return 해주는 JSON data 의 구조를 명확하게 한눈에 확인할 수 있는 방법이기 때문입니다.

2021-02-23 14:22 UTC, jamessoun93 commented on product/views.py
> +            product             = Product.objects.get(id=product_id)
exception handling 꼭 추가되어야 하는 view 입니다 지윤님!!
어떤 exception 발생할 수 있는지 분석해보시고, 핸들링 로직 꼭 추가해주세요 😉

2021-02-23 14:22 UTC, jamessoun93 commented on product/views.py
> +            product     = Product.objects.get(id=product_id)
get() 관련 exception 핸들링 추가해주셔야합니다 지윤님!

2021-02-23 14:22 UTC, jamessoun93 commented on product/views.py
> +                product.save()
이 부분은 REST 규칙에따라 DELETE 메소드로 받아주셔야 합니다. 지금은 똑같은 endpoint 가 호출되면 백엔드에서 확인 후 처리를 해주고 계신데, 이 부분은 프론트와 협의하여 프론트쪽에서 delete 인지 post 인지 구별하여 보내줄 수 있도록 변경해주세요!

2021-02-23 14:22 UTC, jamessoun93 commented on product/views.py
> +            return JsonResponse({'message':'SUCCESS', 'total_likes': total_likes}, status=201)
위 리뷰내용 반영하면 이 부분도 조금 변경사항이 있을거라 생각합니다. 적용해보세요! 😁

2021-02-23 14:22 UTC, jamessoun93 commented on product/views.py
> +
불필요한 empty lines 없애주세요!

2021-02-23 15:27 UTC, yoon1ee commented on product/urls.py
> +# ]
푸쉬하고 발견해서 다시 커밋했는데 이전파일이 먼저 뜨나봐요ㅠ 담 푸쉬때는 주석확인하겠습니다~!

2021-02-23 15:28 UTC, yoon1ee commented on product/views.py
> +
삭제하겠습니다!

2021-02-23 15:29 UTC, yoon1ee commented on product/views.py
> +            popularity_level    = product.maker_info.popularity_level
아..그러네요 ㅋㅋㅋㅋㅋ쓸데없이 중복을..! 수정하겠습니다~

2021-02-23 15:29 UTC, yoon1ee commented on product/views.py
> +                tab_names.append(content.name)
넵!!

2021-02-23 15:30 UTC, yoon1ee commented on product/views.py
> +            ]
수정하겠습니다~~

2021-02-23 15:30 UTC, yoon1ee commented on product/views.py
> +            product             = Product.objects.get(id=product_id)
네에!👍🏼

2021-02-23 15:30 UTC, yoon1ee commented on product/views.py
> +            product     = Product.objects.get(id=product_id)
수정하겠습니다!

2021-02-23 15:31 UTC, yoon1ee commented on product/views.py
> +                product.save()
여기도 수정하겠습니다~

2021-02-23 15:32 UTC, yoon1ee commented on product/views.py
> +            return JsonResponse({'message':'SUCCESS', 'total_likes': total_likes}, status=201)
넵!

2021-02-23 15:34 UTC, yoon1ee commented on product/views.py
> +
다음 푸쉬떄는 지우고 올리겠습니다!

제 코드보다도 긴 리뷰 꼼꼼히 남겨주셔서 감사합니다🥺🥺🥺

2021-02-24 15:27 UTC, jamessoun93 commented
@yoon1ee conflict 해결해주세요!

2021-02-25 09:26 UTC, closed without merging